### ISSUE TITLE
Names are not flowing correctly

### ISSUE THREAD

**Issue by lappalal** [codeuniversity/code-intranet-issues#9]
![image](https://user-images.githubusercontent.com/1348687/31447476-5c0b3678-aea2-11e7-8498-3105230c7ded.png)

They do not flow in a correct way (left bound, center bound, right bound)

**Comment by luhagel** [comment]
Now that's interesting

**Comment by ThePuzzlers** [comment]
1. Get rid of the hard coded style properties
2. They are floating weird because of the margin-left inside of the '.nav-account-label span'. Get rid of it as well
3. To get the space between the Image and the Name back, apply a 'padding-left' to the '.split .flex-8'. But specify it to apply only on the cards, otherwise you will end up with a broken sidebar. 
<img width="1470" alt="screen shot 2017-10-15 at 21 42 14" src="https://user-images.githubusercontent.com/16598375/31588477-66cf06cc-b1f2-11e7-961e-62071d125558.png">
<img width="216" alt="screen shot 2017-10-15 at 21 44 03" src="https://user-images.githubusercontent.com/16598375/31588478-66eda014-b1f2-11e7-892a-1601c5b5b7f2.png">
<img width="215" alt="screen shot 2017-10-15 at 21 45 18" src="https://user-images.githubusercontent.com/16598375/31588479-670cbf8a-b1f2-11e7-8e14-4b248c178504.png">

**Comment by luhagel** [comment]
fixed with next deployment
